### ISSUE TITLE
Can't exit application 

### ISSUE THREAD

**Issue by quentin23soleil** [ImaginativeShohag/Why-Not-Compose#10]
I'm using a pixel with gesture navigation and I can't seem to exit. App always shows the toast to press back again.

**Comment by ImaginativeShohag** [comment]
A quick double-back gesture should close the app. I delayed 500 milliseconds [here](https://github.com/ImaginativeShohag/Why-Not-Compose/blob/f788fa3047c31565e5fa0be832bf9e51bd5c5c22/app/src/main/java/org/imaginativeworld/whynotcompose/ui/screens/MainActivity.kt#L95). You can try increasing the delay and try in your device. I tried in my POCO with the back gesture. It working fine so far.

**Comment by quentin23soleil** [comment]
oh, 500ms is short, but yes, it works. 

(also, it's considered a bad practice to have that kind of behaviour)
