### ISSUE TITLE
Multiple video player in LazyColumn

### ISSUE THREAD

**Issue by hadiyarajesh** [ImaginativeShohag/Why-Not-Compose#2]
It would be a good feature to have multiple exo player in `LazyColumn` such that when one player (nearest from center of screen) is playing, others should be paused. I tried but didn't achieved 100% accuracy. I can share the code if required.

**Comment by ImaginativeShohag** [comment]
You are not alone with this problem. Many people are in this problem. A related issue is tracked here: https://issuetracker.google.com/issues/190920985

I didn't try it yet. Will will check it soon and let's see if any workaround I found will share.

Please share your code.

**Comment by ImaginativeShohag** [comment]
In release [v4](https://github.com/ImaginativeShohag/Why-Not-Compose/releases/tag/v4) I added an ExoPlayer example. Please check it. And give feedback. :)

**Comment by hadiyarajesh** [comment]
seems great. i'll see if i can integrate it with photo + video feed.
